# Polar Cloud nginx configuration snippet
# This should be added inside the server block of your mainsail nginx configuration

# Redirect /polar-cloud to /polar-cloud/ for user-friendliness
location = /polar-cloud {
    return 301 $scheme://$host/polar-cloud/;
}

location /polar-cloud/ {
    alias /home/pi/polar-cloud/web/;
    try_files $uri $uri/ /polar-cloud/index.html;
} 